# Site settings
title: Jekyll One
tag_text: One
description: Jekyll One is a Jekyll theme for single-page websites only.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
